-- Create ASP.NET Identity tables for PostgreSQL
-- This script creates the necessary tables for ASP.NET Identity user management

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

-- Create custom User table for application-specific user data
CREATE TABLE IF NOT EXISTS users (
    id uuid NOT NULL,
    email text NOT NULL,
    display_name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);



-- Create Tasks table
CREATE TABLE IF NOT EXISTS tasks (
    id uuid NOT NULL,
    title text NOT NULL,
    description text,
    status text NOT NULL,
    priority text NOT NULL,
    due_date timestamp with time zone,
    tags jsonb,
    owner_user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_users_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_tasks_owner_user_id ON tasks (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS ix_tasks_due_date ON tasks (due_date);
CREATE INDEX IF NOT EXISTS ix_tasks_owner_status ON tasks (owner_user_id, status);

-- Create Attachments table
CREATE TABLE IF NOT EXISTS attachments (
    id uuid NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    file_size_bytes bigint NOT NULL,
    storage_path text NOT NULL,
    task_id uuid NOT NULL,
    uploaded_by_user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_attachments PRIMARY KEY (id),
    CONSTRAINT fk_attachments_tasks_task_id FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_users_uploaded_by_user_id FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_attachments_task_id ON attachments (task_id);
CREATE INDEX IF NOT EXISTS ix_attachments_uploaded_by_user_id ON attachments (uploaded_by_user_id);

-- Create ReminderLogs table
CREATE TABLE IF NOT EXISTS reminder_logs (
    id uuid NOT NULL,
    task_id uuid NOT NULL,
    user_id uuid NOT NULL,
    reminder_sent_at timestamp with time zone NOT NULL,
    task_due_date timestamp with time zone NOT NULL,
    reminder_type text NOT NULL,
    delivery_successful boolean NOT NULL,
    delivery_details text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_reminder_logs PRIMARY KEY (id),
    CONSTRAINT fk_reminder_logs_tasks_task_id FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_reminder_logs_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_reminder_logs_unique_reminder ON reminder_logs (task_id, reminder_type, task_due_date);
CREATE INDEX IF NOT EXISTS ix_reminder_logs_task_id ON reminder_logs (task_id);
CREATE INDEX IF NOT EXISTS ix_reminder_logs_user_id ON reminder_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_reminder_logs_reminder_sent_at ON reminder_logs (reminder_sent_at);

-- Create audit_events table for audit logging
CREATE TABLE IF NOT EXISTS audit_events (
    id uuid NOT NULL,
    action character varying(50) NOT NULL,
    user_id uuid NOT NULL,
    entity_id uuid,
    entity_type character varying(100),
    details character varying(1000),
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_audit_events PRIMARY KEY (id),
    CONSTRAINT fk_audit_events_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_audit_events_user_id ON audit_events (user_id);
CREATE INDEX IF NOT EXISTS ix_audit_events_created_at ON audit_events (created_at);
CREATE INDEX IF NOT EXISTS ix_audit_events_entity ON audit_events (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_events_action ON audit_events (action);

-- Insert default roles
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") 
VALUES ('1', 'User', 'USER', 'role-user-stamp')
ON CONFLICT ("Id") DO NOTHING;

-- Insert test users
-- Password for both users is: Test123!
-- This is the hashed version of "Test123!" using ASP.NET Identity's PasswordHasher
INSERT INTO "AspNetUsers" (
    "Id", 
    "UserName", 
    "NormalizedUserName", 
    "Email", 
    "NormalizedEmail", 
    "EmailConfirmed", 
    "PasswordHash", 
    "SecurityStamp", 
    "ConcurrencyStamp", 
    "PhoneNumber", 
    "PhoneNumberConfirmed", 
    "TwoFactorEnabled", 
    "LockoutEnd", 
    "LockoutEnabled", 
    "AccessFailedCount"
) VALUES 
(
    '11111111-1111-1111-1111-111111111111',
    'testuser1@example.com',
    'TESTUSER1@EXAMPLE.COM',
    'testuser1@example.com',
    'TESTUSER1@EXAMPLE.COM',
    true,
    'AQAAAAEAACcQAAAAEJ8u3QhvXtV4+O4xNkqvQJ5rJ4LjL8Q8t5eF3A6L9VxN2M8P7R6S1T4U9W0X5Y3Z',
    'TESTUSER1SECURITYSTAMP',
    'testuser1-concurrency',
    null,
    false,
    false,
    null,
    false,
    0
),
(
    '22222222-2222-2222-2222-222222222222',
    'testuser2@example.com',
    'TESTUSER2@EXAMPLE.COM',
    'testuser2@example.com',
    'TESTUSER2@EXAMPLE.COM',
    true,
    'AQAAAAEAACcQAAAAEJ8u3QhvXtV4+O4xNkqvQJ5rJ4LjL8Q8t5eF3A6L9VxN2M8P7R6S1T4U9W0X5Y3Z',
    'TESTUSER2SECURITYSTAMP',
    'testuser2-concurrency',
    null,
    false,
    false,
    null,
    false,
    0
)
ON CONFLICT ("Id") DO NOTHING;

-- Assign both users to the User role
INSERT INTO "AspNetUserRoles" ("UserId", "RoleId") 
VALUES 
    ('11111111-1111-1111-1111-111111111111', '1'),
    ('22222222-2222-2222-2222-222222222222', '1')
ON CONFLICT ("UserId", "RoleId") DO NOTHING;

-- Insert corresponding domain users with matching IDs
INSERT INTO users (id, email, display_name, created_at, updated_at)
VALUES 
    ('11111111-1111-1111-1111-111111111111', 'testuser1@example.com', 'Test User One', NOW(), NOW()),
    ('22222222-2222-2222-2222-222222222222', 'testuser2@example.com', 'Test User Two', NOW(), NOW())
ON CONFLICT (email) DO NOTHING;